FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
COPY tests/requirements.txt tests-requirements.txt

RUN pip install --no-cache-dir -r requirements.txt && \
    pip install -r tests-requirements.txt

COPY . .

ENV PYTHONPATH=/app
ENV TESTING=1